### ISSUE TITLE
memory usage when indexing

### ISSUE THREAD

**Issue by roryk** [bioturing/hera#11]
hera is using more memory than expected when doing the transcriptome indexing:

```
REF=../metadata/Homo_sapiens.GRCh38.dna.toplevel.fa
GTF=../metadata/Homo_sapiens.GRCh38.89.gtf
mkdir -p hera_index
hera_build --fasta ${REF} --gtf ${GTF} --outdir hera_index
```
here is the output from LSF after it killed the job:

```
Resource usage summary:

    CPU time   :    395.88 sec.
    Max Memory :     48979 MB
    Max Swap   :     49346 MB
```

Any tips? Thanks!

**Comment by kspham** [comment]
Thanks Rory for the bug report. Please use param --grch38 1 to handle this special case.  (./hera_build  --fasta Homo_sapiens.GRCh38.dna.toplevel.fa --gtf Homo_sapiens.GRCh38.89.gtf --outdir index38/ --grch38 1)

And please let us know if it works!
Thanks,

**Comment by roryk** [comment]
Thanks! It looks like this fixed the indexing issue.
