### ISSUE TITLE
hera segfault

### ISSUE THREAD

**Issue by roryk** [bioturing/hera#12]
Heya-- the recent fixes fixed the GRCh38 index issue, but hera-quant segfaults:

```
 hera quant -i hera_index -o SRR1548811 fastq/SRR1548811_1.fastq fastq/SRR1548811_2.fastq
```

hera_index is the GRCh38 index.

ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR154/001/SRR1548811/SRR1548811_1.fastq.gz
ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR154/001/SRR1548811/SRR1548811_2.fastq.gz

are the two FASTQ files. Thanks!

**Comment by GinnyAquarius** [comment]
hi roryk ,
Please try again with '/' after -o SRR1548811 (-o SRR1548811/) and tell us if it can work. This error should be fixed in this version as we expected, but it seem to be not.
Thank you for informing us.

**Comment by roryk** [comment]
Hi Ginny! Thanks so much for the quick reply. That totally fixed it.
