### ISSUE TITLE
Hera from Bioconda crashes on me

### ISSUE THREAD

**Issue by holtgrewe** [bioturing/hera#13]
I'm using v1.0.1 from Bioconda and the GRCh38 downloaded index with hs38.fa.

I'm putting the RNA-seq from here into Hera: https://www.encodeproject.org/experiments/ENCSR001UXR/

Am I doing anything wrong? Does this work for you?

Edit: The ticket was a crash because of missing file names on the command line. However, Hera crashes on me regardlessly of what I do.

**Comment by GinnyAquarius** [comment]
hi holtgrewe,
Can you give us more detail about your command? We have run hera on your sample ENCLB020LQS and it work well for both transcriptome:

```
./build/hera quant -i index38 -t 32 ENCFF386MOY.fastq.gz ENCFF541KUW.fastq.gz 
Hera is a program developed by BioTuring for RNA-Seq analysis.
Please contact info@bioturing.com if you need further support
Process paired-end reads in:
	 1. ENCFF386MOY.fastq.gz
	 2. ENCFF541KUW.fastq.gz
Number of aligned pairsr: 19107286/26087337     
Mean read length	: 101.000000
Mean fragment length	: 154.022693
Finish EM with 54 rounds
```

and transcriptome + genome: 

```
./build/hera quant -i index38 -t 32 -f index38/GRCh38.fa ENCFF386MOY.fastq.gz ENCFF541KUW.fastq.gz 
Hera is a program developed by BioTuring for RNA-Seq analysis.
Please contact info@bioturing.com if you need further support
Process paired-end reads in:
	 1. ENCFF386MOY.fastq.gz
	 2. ENCFF541KUW.fastq.gz
Number of aligned pairsr: 22306580/26087337     
Mean read length	: 101.000000
Mean fragment length	: 155.960055
Finish EM with 53 rounds
```
or could you pull latest code from hera repository and check if it can work?

Thank you,
BioTuring Algorithm Team

**Comment by holtgrewe** [comment]
Hi, the problem was because I did not reserve enough memory on our SGE cluster system.

**Comment by kspham** [comment]
Holtgrewe, how much memory do you have on the machine?

**Comment by holtgrewe** [comment]
The machine has 160GB but I put a too low limit on vmem (the job is then limited by `ulimit -v`). With increased limit it works now.
