### ISSUE TITLE
os import error in hera_build v1.1

### ISSUE THREAD

**Issue by aswathyseb** [bioturing/hera#16]
Hello,

I am using hera v1.1 and when running hera_build command, it gives me 'os' not defined error.

Traceback (most recent call last):
  File "/home/aswathy/miniconda3/envs/bioinfo/bin/hera_build", line 219, in <module>
    write_index(total_byte, gene_info)
  File "/home/aswathy/miniconda3/envs/bioinfo/bin/hera_build", line 121, in write_index
    if not os.path.exists(outdir):
NameError: name 'os' is not defined

Thanks,

**Comment by GinnyAquarius** [comment]
hi aswathyseb,
Thank you for informing us, we have fixed the bug, can you pull or clone hera again and check if it can work now?

**Comment by aswathyseb** [comment]
Hi,

I cloned it again and now it ran successfully.

Thank you for your help.
