### ISSUE TITLE
Processing split libraries

### ISSUE THREAD

**Issue by holtgrewe** [bioturing/hera#17]
How can I give more than one file each for the left and right end reads? E.g., when having an experiment split over multiple lanes?

**Comment by kspham** [comment]
Hi Manuel,
A temporary solution is to concatenate these multiple files into a single one and run hera.  `cat x1_lane1 x1_lane x1_lane3 > x_1.fastq `

**Comment by holtgrewe** [comment]
Hi Son, that's what I'm currently doing. However, as in all NGS processing I/O is the bottleneck and killing me ;) It would be great if there was an option to either specify a file with file names or allow a multi-argument parameter, e.g., `-1 lane1_1.fastq.gz lane2_1.fastq.gz -2 lane1_2.fastq.gz lane2_2.fastq.gz`.

**Comment by bioturing** [comment]
Thank you, Manuel! This option will be available soon.
Son.

On Tue, Sep 12, 2017 at 11:45 PM, Manuel Holtgrewe <notifications@github.com

**Comment by bioturing** [comment]
Manuel, please built the latest version from source code and this option is submitted. Files in different lanes are separated by commas ','.
