### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by micknudsen** [bioturing/hera#6]
Hi,

I have tried running Hera on few samples, but it always crashes with a segmentation fault. No other log output is available, so I cannot be more precise about the error. It seems to happen at random times (I have rerun the same sample multiple times).

Any ideas?

**Comment by kspham** [comment]
Is there any possibility for you to share your data with us so we could reproduce and fix the issue?

**Comment by kspham** [comment]
Also, could you tell us a little bit more information about the system that you run hera on?

**Comment by micknudsen** [comment]
Unfortunately, I only have clinical in-house data (which I cannot share). I will try to dig up some RNA data from the public domain and see if I can reproduce the error. Stay tuned!

**Comment by micknudsen** [comment]
I run Hera as Slurm jobs on a CentOS HPC cluster (http://genome.au.dk/system-info/).

**Comment by kspham** [comment]
Thank you for your bug report & help to trace the source of the error!

**Comment by GinnyAquarius** [comment]
Hi micknudsen,

Jemalloc on Centos could be the cause of the instability. We currently turn it off for stability purpose. Hence, the program should consume a little more memory (1-2GB). Please pull or clone again to check if it works. 

Best,
Bioturing Algorithm Team.

**Comment by bioturing** [comment]
Micknudsen, Hopefully, the new fix solves the segmentation fault problem?

**Comment by micknudsen** [comment]
I am running a test right now. I will let you know as soon as it finishes or (hopefully not) crashes.

**Comment by micknudsen** [comment]
Problem solved. Thanks!
