### ISSUE TITLE
feature request - output prefix

### ISSUE THREAD

**Issue by colindaven** [bioturing/hera#9]
Hi,

I would like to batch process a lot of files and load them into a genome browser. It would be great to not have to rename each file manually. I hope it would be feasible to add a output prefix option so output from many samples can be created in the same directory.

eg 
`sample1_abundance.tsv`
`sample1_fusion.bedpe`

Thanks
Colin

**Comment by kspham** [comment]
Hi Colin,
We have released a new version (1.0.1) that has this feature. Please download and use the new version.
Thank you!
